<?php

/**
 * Class AlamatCustom
 */

class AlamatCustom extends Alamat
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'alamat_1' => 'Alamat (Jalan/RT/RW)',
            'alamat_2' => 'Alamat (Perumahan/Kelurahan)',
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function getProvince() {
        $model = ProvinceCustom::model()->findByPk($this->provinsi);
        if (!empty($model)) {
            return $model->name;
        } else {
            return null;
        }
    }

    public function getRegency() {
        $model = RegencyCustom::model()->findByPk($this->kota);
        if (!empty($model)) {
            return $model->name;
        } else {
            return null;
        }
    }

    public function getDistrict() {
        $model = DistrictCustom::model()->findByPk($this->kecamatan);
        if (!empty($model)) {
            return $model->name;
        } else {
            return null;
        }
    }
}