<?php
/**
 * Class BerkasAkreditasiCustom
 */

class BerkasAkreditasiCustom extends BerkasAkreditasi
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'created_at' => 'Waktu Upload',
            'created_by' => 'Diupload Oleh'
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id_pengajuan',$this->id_pengajuan);
        $criteria->compare('tipe_berkas',$this->tipe_berkas);
        $criteria->compare('file_path',$this->file_path,true);
        $criteria->compare('deskripsi',$this->deskripsi,true);
        $criteria->compare('created_by',$this->created_by,true);
        $criteria->compare('created_at',$this->created_at,true);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
        ));
    }

    public function getTipeBerkas() {
        $options = DocumentType::getAllDocumentTypeOptions();
        return $options[$this->tipe_berkas];
    }
}