<?php
/**
 * Class FasilitasKlinikCustom
 */

class FasilitasKlinikCustom extends FasilitasKlinik
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllPenyelenggaraanOptions() {
        return array(
            'rawat_inap' => 'Rawat Inap',
            'non_rawat_inap' => 'Non Rawat Inap'
        );
    }
}