<?php
/**
 * Class KontakCustom
 */

class KontakCustom extends Kontak
{
    public function rules()
    {
        $rules = parent::rules();
        return array_merge($rules, array(
            array('no_telp', 'required')
        ));
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function isComplete() {
        return $this->validate();
    }
}