<?php
/**
 * Class PendampingCustom
 */

class PendampingCustom extends Pendamping
{
    public function rules()
    {
        return parent::rules();
    }

    public function attributeLabels()
    {
        return array(
            'created_at' => 'Waktu Entri',
            'created_by' => 'Dibuat Oleh',
            'updated_at' => 'Terakhir Diperbarui',
            'updated_by' => 'Diperbarui Oleh'
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function getTipe() {
        $options = TipePendamping::getAllTipeOptions();
        if (!empty($this->tipe)) {
            return $options[$this->tipe];
        } else {
            return null;
        }
    }

    public static function getCurrentlyLogin() {
        $model = PendampingCustom::model()->findByAttributes(array('id_user'=>Yii::app()->user->getId()));
        return $model;
    }
}