<?php
/**
 * Class PengajuanAkreditasiCustom
 */

class PengajuanAkreditasiCustom extends PengajuanAkreditasi
{
    public $id_regency;
    public $nama_klinik;

    public function rules()
    {
        return array_merge(
            parent::rules(),
            array(
                array('nama_klinik, id_regency','safe')
            )
        );
    }

    public function attributeLabels()
    {
        return array(
            'tgl_pengajuan' => 'Tanggal Pengajuan',
            'jenis_pengajuan' => 'Jenis Usulan '
        );
    }

    /**
     * @param string $className
     * @return PengajuanAkreditasiCustom
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getInstance() {
        $klinik = KlinikCustom::getInstance();
        $model = self::model()->findByAttributes(array(
            'id_klinik' => $klinik->id,
            'status' => array(StatusPengajuan::DRAFT, StatusPengajuan::DIAJUKAN, StatusPengajuan::VISIT, StatusPengajuan::DITERIMA)
        ));
        if (empty($model)) {
            $model = new PengajuanAkreditasiCustom();
            $model->id_klinik = $klinik->id;
            $model->status = StatusPengajuan::DRAFT;
            $model->save();
        }
        return $model;
    }

    public static function getAllJenisPengajuanOptions() {
        return array(
            'pertama' => 'Usulan Pertama',
            'remedial' => 'Remedial',
            'perpanjangan' => 'Perpanjangan'
        );
    }

    public function getJenisPengajuan() {
        $options = self::getAllJenisPengajuanOptions();
        return $options[$this->jenis_pengajuan];
    }

    public function hasDocuments() {
        $docs = BerkasAkreditasiCustom::model()->countByAttributes(array(
            'id_pengajuan'=>$this->id
        ));
        return $docs;
    }

    /**
     * @return int|mixed
     * @throws CException
     */
    public function getLastNoUrut() {
        $cmd = Yii::app()->db->createCommand('SELECT MAX(no_urut) FROM pengajuan_akreditasi');
        $no_urut = $cmd->queryScalar();
        if (empty($no_urut)) {
            return 1;
        }
        else return $no_urut+1;
    }

    public function getStatus() {
        $options = StatusPengajuan::getAllStatusPengajuanOptions();
        return $options[$this->status];
    }

    public static function countAll() {
        $criteria = new CDbCriteria();
        $criteria->condition = 'no_urut IS NOT NULL';
        $criteria->compare('status', array(StatusPengajuan::DIAJUKAN, StatusPengajuan::DITERIMA, StatusPengajuan::VISIT));
        if (Yii::app()->user->isSudin() || Yii::app()->user->isPendamping()) {
            $criteria->join = 'left join klinik t2 on t2.id = t.id_klinik left join alamat t3 on t3.id_klinik = t2.id';
            $criteria->compare('t3.kota', Yii::app()->user->regency_id);
        }
        return self::model()->count($criteria);
    }

    public static function countAllCanceled() {
        $criteria = new CDbCriteria();
        $criteria->condition = 'no_urut IS NOT NULL';
        if (Yii::app()->user->isSudin()) {
            $criteria->join = 'left join klinik t2 on t2.id = t.id_klinik left join alamat t3 on t3.id_klinik = t2.id';
            $criteria->compare('t3.kota', Yii::app()->user->regency_id);
        }
        $criteria->compare('status', array(StatusPengajuan::BATAL, StatusPengajuan::DITOLAK));
        return self::model()->count($criteria);
    }

    public static function countAllAccept() {
        $criteria = new CDbCriteria();
        $criteria->condition = 'no_urut IS NOT NULL';
        if (Yii::app()->user->isSudin()) {
            $criteria->join = 'left join klinik t2 on t2.id = t.id_klinik left join alamat t3 on t3.id_klinik = t2.id';
            $criteria->compare('t3.kota', Yii::app()->user->regency_id);
        }
        $criteria->compare('status', array(StatusPengajuan::REKOMENDASI));
        return self::model()->count($criteria);
    }

    /**
     * @return CActiveDataProvider
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->condition = 'no_urut IS NOT NULL';

        $criteria->compare('id',$this->id);
        $criteria->compare('t.id_klinik',$this->id_klinik);
        $criteria->compare('tgl_pengajuan',$this->tgl_pengajuan,true);
        $criteria->compare('jenis_pengajuan',$this->jenis_pengajuan,true);
        $criteria->compare('tgl_penetapan',$this->tgl_penetapan,true);
        $criteria->compare('status',$this->status);
        $criteria->compare('status_info',$this->status_info);
        $criteria->compare('status_alamat',$this->status_alamat);
        $criteria->compare('status_kontak',$this->status_kontak);
        $criteria->compare('status_fasilitas',$this->status_fasilitas);
        $criteria->compare('status_foto',$this->status_foto);
        $criteria->compare('status_dokumen',$this->status_dokumen);
        $criteria->join = 'left join klinik t2 ON t.id_klinik = t2.id left join alamat t3 on t3.id_klinik = t2.id';
        if (Yii::app()->user->isSudin()) {
            $criteria->compare('t3.kota', Yii::app()->user->regency_id);
        }
        $criteria->compare('t2.nama', $this->nama_klinik, true);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>'no_urut ASC'
            )
        ));
    }

    /**
     * @return CActiveDataProvider
     */
    public function searchForDashboard()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id',$this->id);
        $criteria->compare('id_klinik',$this->id_klinik);
        $criteria->compare('no_urut',$this->no_urut);
        $criteria->compare('tgl_pengajuan',$this->tgl_pengajuan,true);
        $criteria->compare('jenis_pengajuan',$this->jenis_pengajuan,true);
        $criteria->compare('tgl_penetapan',$this->tgl_penetapan,true);
        $criteria->compare('status',$this->status);
        $criteria->compare('status_info',$this->status_info);
        $criteria->compare('status_alamat',$this->status_alamat);
        $criteria->compare('status_kontak',$this->status_kontak);
        $criteria->compare('status_fasilitas',$this->status_fasilitas);
        $criteria->compare('status_foto',$this->status_foto);
        $criteria->compare('status_dokumen',$this->status_dokumen);

        if (Yii::app()->user->isSudin()) {
            $criteria->join = 'left join klinik t2 ON t.id_klinik = t2.id left join alamat t3 on t3.id_klinik = t2.id';
            $criteria->compare('t3.kota', Yii::app()->user->regency_id);
        }

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
            'pagination'=>array('pageSize'=>5),
            'sort'=>array(
                'defaultOrder'=>'no_urut ASC'
            )
        ));
    }

    public function searchForRiwayat()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->condition = 'no_urut IS NOT NULL';

        $criteria->compare('id',$this->id);
        $criteria->compare('t.id_klinik',$this->id_klinik);
        $criteria->compare('tgl_pengajuan',$this->tgl_pengajuan,true);
        $criteria->compare('jenis_pengajuan',$this->jenis_pengajuan,true);
        $criteria->compare('tgl_penetapan',$this->tgl_penetapan,true);
        $criteria->compare('status',$this->status);
        $criteria->compare('status_info',$this->status_info);
        $criteria->compare('status_alamat',$this->status_alamat);
        $criteria->compare('status_kontak',$this->status_kontak);
        $criteria->compare('status_fasilitas',$this->status_fasilitas);
        $criteria->compare('status_foto',$this->status_foto);
        $criteria->compare('status_dokumen',$this->status_dokumen);
        $criteria->join = 'left join klinik t2 ON t.id_klinik = t2.id left join alamat t3 on t3.id_klinik = t2.id';
        if (Yii::app()->user->isSudin()) {
            $criteria->compare('t3.kota', Yii::app()->user->regency_id);
        }
        $criteria->compare('t2.nama', $this->nama_klinik, true);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>'id DESC'
            )
        ));
    }

    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'berkasAkreditasis' => array(self::HAS_MANY, 'BerkasAkreditasiCustom', 'id_pengajuan'),
            'idKlinik' => array(self::BELONGS_TO, 'KlinikCustom', 'id_klinik'),
        );
    }
}