<?php
/**
 * Class RiwayatPendidikanCustom
 */

class RiwayatPendidikanCustom extends RiwayatPendidikan
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllTingkatOptions() {
        return array(
            'DI' => 'Diploma I',
            'DII' => 'Diploma II',
            'DIII' => 'Diploma III',
            'DIV' => 'Diploma IV',
            'S1'=>'Sarjana',
            'Profesi' => 'Profesi',
            'Sp' => 'Spesialisasi',
            'S2'=>'Master',
            'S3'=>'Doktor'
        );
    }
}