<?php
/**
 * Class SAResumeCustom
 */

class SAResumeCustom extends SaResume
{
    public $max_score;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'created_at' => 'Waktu Input',
            'updated_at' => 'Terakhir Diberbarui',
            'score' => 'Total Skor',
            'max_score' => 'Skor Maksimum',
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function getMaxScore() {
        $score = SAScoreMaximum::getAllMaxScoreOptions();
        return $score[$this->bab];
    }

    public function getProgress() {
        if (!empty($this->score)) {
            $tmp = round($this->score/$this->getMaxScore()*100, 2);
            return $tmp.' %';
        } else {
            return '0 %';
        }
    }

    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id',$this->id);
        $criteria->compare('id_pengajuan',$this->id_pengajuan);
        $criteria->compare('bab',$this->bab,true);
        $criteria->compare('score',$this->score);
        $criteria->compare('created_at',$this->created_at,true);
        $criteria->compare('created_by',$this->created_by,true);
        $criteria->compare('updated_at',$this->updated_at,true);
        $criteria->compare('updated_by',$this->updated_by,true);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
        ));
    }
}