<?php
/**
 * Class SAResumeCustom
 */

class SAResumeCustom extends SaResume
{
    public $max_score;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'created_at' => 'Waktu Input',
            'updated_at' => 'Terakhir Diberbarui',
            'score' => 'Total Skor',
            'max_score' => 'Skor Maksimum',
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function getMaxScore() {
        $score = SAScoreMaximum::getAllMaxScoreOptions();
        return $score[$this->bab];
    }
}